project:
  type: book
  output-dir: docs
execute:
  cache: false
  freeze: auto
book:
  title: "Protección sanitaria de cereales de invierno"
  subtitle: "Sudeste de Buenos Aires - Campaña 2022"
  search: false
  page-footer: 
    border: false
    background: light
    left: "Red protección sanitaria de cereales de invierno - Sudeste de Bs As"
       
  chapters:
    - index.qmd
    - meteo.qmd
    - cura.qmd
    - foliares.qmd

format:
  html:
    toc: true
    toc-depth: 5
    theme: 
      light: cosmo
      dark: superhero
