# Consideraciones finales {.unnumbered}

La campaña 2022 de grano fino presentó anormalidades meteorológicas generando variabilidad de condiciones en la región Mar y Sierras. Por un lado, lotes con elevados daños de heladas potenciado por estrés hídrico en zonas continentales y en suelos someros y con nula o baja presión de enfermedades (sitios experimentales de Tandil y La Dulce), y por otro, cultivos con rendimientos normales, por lo general ubicados en zonas costeras, y con ambiente favorable para enfermedades. 

Los tratamientos curasemillas no evidenciaron diferencias notorias en parámetros vegetativos, aunque ofrecieron algunas tendencias en el rendimiento, que no se lograron expresar estadísticamente, probablemente por la baja potencia de los diseños (nro de repeticiones o replicas de ensayos). Estos factores podrian ser mejorados en futuros años experimentales (llevar a 4 repeticiones y replicar mas ensayos), con el objetivo de aumentar la potencia estadistica del análisis. 

En cambio, los tratamientos foliares, aun con baja presión de enfermedades, lograron expresar diferencias entre tratamientos, poniendo en evidencia el impacto del resguardo del área foliar en el cultivo de trigo y cebada. 

