---
title: "curasemillas"
format: html
---

# Setup 
```{r}
# https://github.com/juanchiem/apptest2/blob/master/app.R
library(tidyverse)
library(gsheet)
library(janitor)
library(patchwork)
conflicted::conflict_prefer("filter", "dplyr")
conflicted::conflict_prefer("select", "dplyr")
```

```{r}
library(lme4)
library(emmeans)
```

# Dataset
## meta 

```{r}
# meta_cura <- gsheet2tbl("https://docs.google.com/spreadsheets/d/165Mu7j6k2QVZN4NPJvy42-WCj8WyH4C-flKlEF-NB4Y/edit#gid=663634411") 
# meta_cura %>% rio::export("data/meta_cura.csv")
meta_cura <-  read.csv("data/meta_cura.csv")
```

## trat

```{r}
# trat_cura <- gsheet2tbl("https://docs.google.com/spreadsheets/d/165Mu7j6k2QVZN4NPJvy42-WCj8WyH4C-flKlEF-NB4Y/edit#gid=1796511474")
# trat_cura %>% rio::export("data/trat_cura.csv")
trat_cura <- read.csv("data/trat_cura.csv")%>% 
    mutate(trat_id = stringr::str_to_upper(trat)) 
```

## plots
```{r}
plots_cura <- gsheet2tbl("https://docs.google.com/spreadsheets/d/165Mu7j6k2QVZN4NPJvy42-WCj8WyH4C-flKlEF-NB4Y/edit#gid=1847280538")
# write.table(plots_cura, "data/plots_cura.csv",
#             na = "", row.names = FALSE, col.names = FALSE, append = TRUE, sep = ",")
# plots_cura <- read.csv("data/plots_cura.csv")

# plots_cura %>% 
#   # filter(regional==input$regional) %>%
#   # filter(regional=="tandilia") %>%
#   mutate(y=factor(y)) %>% 
#   select(-regional) %>% 
#   remove_empty() 
```

## Cobertura

```{r}
"https://docs.google.com/spreadsheets/d/165Mu7j6k2QVZN4NPJvy42-WCj8WyH4C-flKlEF-NB4Y/edit#gid=1038456513" %>% 
  # browseURL()
  gsheet::gsheet2tbl() -> cober_raw
```

```{r}
cober_raw %>% str
```

```{r, eval=FALSE}
# cober_dat <- cober_raw %>%
#       # filter(regional=="tandilia") %>%
#       # filter(regional=="necochea") %>%
#       pivot_longer(cols=contains("x"), names_to = "x", values_to = "val",
#                    names_prefix = "x") %>%
#       drop_na(val) %>%
#       left_join(plots_cura %>%
#                   pivot_longer(cols=contains("x"),
#                                names_to = "x",
#                                values_to = "crop_trat",
#                                names_prefix = "x")) %>%
#       separate(crop_trat,
#                into = c("crop", "trat"),
#                sep = "(?<=[A-Za-z])(?=[0-9])",
#                remove = F) %>%
#       mutate(crop = fct_rev(factor(crop)),
#              coords = paste(x, y, sep=","),
#              x = as.numeric(x))  %>%
#       left_join(trat_cura %>% select(regional, crop_trat, trat_id)) %>%
# rio::export("data/cober_dat.csv")
```

```{r}
cober_dat <- read.csv("data/cober_dat.csv")
```

```{r}
cober_dat %>% 
  mutate(regional = stringr::str_to_upper(regional)) %>% 
  mutate(crop = if_else(crop=="C", "Cebada", "Trigo")) %>% 
  ggplot()+
  aes(x=trat_id, y= val)+
  facet_grid(regional~crop, scales="free")+
  stat_summary(fun = "mean", geom = "crossbar", col="green", alpha=.1)+
  stat_summary(aes(label=round(..y..)), fun=mean, geom="text") +
  geom_point(alpha=.4)+
  labs(y="%", x="", col = "Tablón") + 
  theme_bw()+
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) + 
  coord_flip()
```

```{r}
ftable(xtabs(~ crop + trat_id + regional, cober_dat))
asin_tran <- make.tran("asin.sqrt", 100)
```

# Trigo 

```{r}
cober_dat %>% 
  distinct(regional, crop, trat_id) %>% 
  filter(regional=="necochea") %>% 
  filter(crop=="T") %>%
  select(-regional) %>% 
  left_join(cober_dat) -> cober_T6
```

```{r}
# mod_T6 <- lme(
#   val ~ trat_compact, 
#   correlation = corExp(form = ~(x+y)),
#   weights = varPower(form = ~fitted(.)),
#   random = list(~1|regional), 
#   data = cober_T6)
# plot(mod_T6)
# car::Anova(mod_T6)
# emmeans(mod_T6, ~ trat_compact, type = "response") %>% plot()
# emmeans(mod_T6, ~ trat_compact, type = "response") %>% 
#   cld(., Letters = letters, alpha = .1, type = "response", reversed = T)
```

```{r}
lmer_T6  <- with(asin_tran, 
                lmer(linkfun(val) ~ trat_id + (1|regional), 
                     data = cober_T6))
plot(lmer_T6)
car::Anova(lmer_T6)
emmeans(lmer_T6, ~ trat_id, type = "response") %>% 
  cld(., Letters = letters, alpha = .1, reversed = T)
```

```{r}
cober_T6 %>% 
  mutate(regional = stringr::str_to_upper(regional)) %>% 
  ggplot() + 
  aes(x=trat_id, y= val)+
  facet_grid(.~regional)+
  stat_summary(fun = "mean", geom = "crossbar", col="green", alpha=.1)+
  stat_summary(aes(label=round(..y..)), fun=mean, geom="text") +
  geom_point(alpha=.4, shape=1)+
  labs(y="%", x="", col = "Tablón") + 
  theme_bw()+
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))+
  coord_flip()
```


```{r}
cober_dat %>% 
  distinct(regional, crop, trat_id) %>% 
  filter(regional!="necochea") %>% 
  filter(crop=="T") %>%
  select(-regional) %>% 
  left_join(cober_dat) -> cober_T2
```

```{r}
# mod_T6 <- lme(
#   val ~ trat_compact, 
#   correlation = corExp(form = ~(x+y)),
#   weights = varPower(form = ~fitted(.)),
#   random = list(~1|regional), 
#   data = cober_T6)
# plot(mod_T6)
# car::Anova(mod_T6)
# emmeans(mod_T6, ~ trat_compact, type = "response") %>% plot()
# emmeans(mod_T6, ~ trat_compact, type = "response") %>% 
#   cld(., Letters = letters, alpha = .1, type = "response", reversed = T)
```

```{r}
lmer_T2  <- with(asin_tran, 
                lmer(linkfun(val) ~ trat_id + (1|regional), 
                     data = cober_T2))
plot(lmer_T2)
car::Anova(lmer_T2)
emmeans(lmer_T2, ~ trat_id, type = "response") %>% 
  cld(., Letters = letters, alpha = .1, reversed = T)
```

```{r}
cober_T2 %>% 
  mutate(regional = stringr::str_to_upper(regional)) %>% 
  ggplot() + 
  aes(x=trat_id, y= val)+
  facet_grid(.~regional)+
  stat_summary(fun = "mean", geom = "crossbar", col="green", alpha=.1)+
  stat_summary(aes(label=round(..y..)), fun=mean, geom="text") +
  geom_point(alpha=.4, shape=1)+
  labs(y="%", x="", col = "Tablón") + 
  theme_bw()+
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))+
  coord_flip()
```

# Cebada 

```{r}
cober_dat %>% 
  distinct(regional, crop, trat_id) %>% 
  filter(crop=="C") %>%
  filter(regional=="necochea") %>% 
  select(-regional) %>% 
  left_join(cober_dat) -> cober_C6
```


```{r}
mod_C6  <- with(asin_tran, 
                lmer(linkfun(val) ~ trat_id + (1|regional), 
                     data = cober_C6))
plot(mod_C6)
car::Anova(mod_C6)
emmeans(mod_C6, ~ trat_id, type = "response") %>% 
  cld(., Letters = letters, alpha = .1, reversed = T)
```


```{r}
cober_C6 %>%
  mutate(regional = stringr::str_to_upper(regional)) %>% 
  # filter(regional=="JMF")
  ggplot() + 
  aes(x=trat_id, y= val)+
  facet_grid(.~regional)+
  stat_summary(fun = "mean", geom = "crossbar", col="green", alpha=.1)+
  stat_summary(aes(label=round(..y..)), fun=mean, geom="text") +
  geom_point(alpha=.4, shape=1)+
  labs(y="%", x="", col = "Tablón") + 
  theme_bw()+
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))+
  coord_flip()
```


```{r}
cober_dat %>% 
  filter(crop=="C") %>%
  filter(regional!="necochea") %>% 
  filter(trat_id!="SISTIVA_PREMIS + ALLTEC_ZN") %>% 
  select(-regional) %>% 
  left_join(cober_dat) -> cober_C2
```


```{r}
mod_C2  <- with(asin_tran, 
                lmer(linkfun(val) ~ trat_id + (1|regional), 
                     data = cober_C2))
plot(mod_C2)
car::Anova(mod_C2)
emmeans(mod_C2, ~ trat_id, type = "response") %>% 
  cld(., Letters = letters, alpha = .1, reversed = T)
```


```{r}
cober_C6 %>%
  mutate(regional = stringr::str_to_upper(regional)) %>% 
  # filter(regional=="JMF")
  ggplot() + 
  aes(x=trat_id, y= val)+
  facet_grid(.~regional)+
  stat_summary(fun = "mean", geom = "crossbar", col="green", alpha=.1)+
  stat_summary(aes(label=round(..y..)), fun=mean, geom="text") +
  geom_point(alpha=.4, shape=1)+
  labs(y="%", x="", col = "Tablón") + 
  theme_bw()+
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))+
  coord_flip()
```
