---
title: "Datasets"
editor_options: 
  chunk_output_type: console
---

```{r, include=FALSE}
library(dplyr)
library(huxtable)
knitr::opts_chunk$set(echo = F, warning = FALSE, message = FALSE)
```

```{r app, eval=FALSE}
"https://github.com/juanchiem/apptest2/blob/master/app.R" %>% browseURL()
```

## trt_list

```{r}
# google_file %>%
#   read_sheet(sheet = "trt_list", range = "A:E") %>%
#   arrange(sitio, cultivo, protec, trt) %>% 
#   rio::export("data/trt_list.csv") 

trt_list <- rio::import("data/trt_list.csv")
```

## Curasemillas

```{r Meta, eval=FALSE}
# gsheet::gsheet2tbl("https://docs.google.com/spreadsheets/d/165Mu7j6k2QVZN4NPJvy42-WCj8WyH4C-flKlEF-NB4Y/edit#gid=663634411") %>% 
# rio::export("data/meta_cura.csv")
meta_cura <- read.csv("data/meta_cura.csv")
```

```{r Cura-trat, eval=FALSE}
# gsheet::gsheet2tbl("https://docs.google.com/spreadsheets/d/165Mu7j6k2QVZN4NPJvy42-WCj8WyH4C-flKlEF-NB4Y/edit#gid=1796511474") %>%  
#   mutate(prod = stringr::str_to_upper(prod)) %>% 
#   arrange(sitio, cultivo, protec, trt) 
trat_cura <- read.csv("data/trat_cura.csv") %>% 
```

```{r cura-croquis, eval=FALSE}
# gsheet::gsheet2tbl("https://docs.google.com/spreadsheets/d/165Mu7j6k2QVZN4NPJvy42-WCj8WyH4C-flKlEF-NB4Y/edit#gid=1847280538") %>% 
#   write.table("data/plots_cura.csv",
#             na = "", row.names = FALSE, col.names = FALSE, append = TRUE, sep = ",")
# plots_cura <- read.csv("data/plots_cura.csv")

# plots_cura %>%
  # filter(regional==input$regional) %>%
  # filter(regional=="tandilia") %>%
  # mutate(y=factor(y)) %>%
  # select(-regional) %>%
  # remove_empty()
```

### Cobertura

```{r eval=FALSE}
# "https://docs.google.com/spreadsheets/d/165Mu7j6k2QVZN4NPJvy42-WCj8WyH4C-flKlEF-NB4Y/edit#gid=1038456513" %>%
#   # browseURL()
#   gsheet::gsheet2tbl() -> cober_raw
# cober_dat <- cober_raw %>%
#       # filter(regional=="tandilia") %>%
#       # filter(regional=="necochea") %>%
#       pivot_longer(cols=contains("x"), names_to = "x", values_to = "val",
#                    names_prefix = "x") %>%
#       drop_na(val) %>%
#       left_join(plots_cura %>%
#                   pivot_longer(cols=contains("x"),
#                                names_to = "x",
#                                values_to = "crop_trat",
#                                names_prefix = "x")) %>%
#       separate(crop_trat,
#                into = c("crop", "trat"),
#                sep = "(?<=[A-Za-z])(?=[0-9])",
#                remove = F) %>%
#       mutate(crop = fct_rev(factor(crop)),
#              coords = paste(x, y, sep=","),
#              x = as.numeric(x))  %>%
#       left_join(trat_cura %>% select(sitio, crop_trat, trat_id)) %>%
# rename(cultivo=crop, prod=trat_id) %>%
#     mutate(cultivo = if_else(cultivo=="C", "Cebada", "Trigo"))
# rio::export("data/cober_dat.csv")

cober_dat <- read.csv("data/cober_dat.csv") %>% 
  dplyr::filter(prod!="SISTIVA_PREMIS_2X") 

cober_dat %>% 
  select(sitio, cultivo, trat, prod, x, y, coords,	val) %>% 
  as_hux() %>% 
  set_font_size(9) %>% 
  theme_compact() %>% 
  set_tb_padding(.05) %>% 
  set_number_format(0)

```

### Rendimiento

```{r eval=FALSE}
# rinde_cura <- raw_rinde %>% 
#   filter(protec=="semilla") %>% 
#   left_join(trat_cura)
# rinde_cura %>% rio::export("data/rinde_cura.csv")

# rio::import("data/rinde_cura.csv") %>%
#   select(sitio, cultivo, trt, prod, bq, kg_ha) %>%  filter(!(sitio=="La Dulce" & cultivo =="trigo" & trt ==3 & kg_ha > 2700)) %>% 
#   add_case(sitio="MDP", cultivo="trigo", trt=10, prod="CHECK", bq=1, kg_ha=3819) %>% 
#   group_by(cultivo, sitio, prod, bq) %>% 
#   summarise(kg_ha=mean(kg_ha)) %>% 
#   filter(!prod=="SISTIVA_PREMIS_2X") %>%
#   ungroup() %>% 
#   rio::export("data/rinde_cura_dat.csv")
# rinde_cura %>% 
#   # select(sitio, cultivo, prod, bq, kg_ha) %>% 
#   filter(cultivo=="trigo") %>% 
#   filter(sitio!="Tandil") %>% 
#   filter(prod %in% c("CHECK"))
# ftable(xtabs(~ cultivo + prod + sitio, rinde_cura %>% droplevels()))
```

```{r}
rinde_cura <- rio::import("data/rinde_cura_dat.csv")
rinde_cura %>% 
  as_hux() %>% 
  set_font_size(9) %>% 
  theme_compact() %>% 
  set_tb_padding(.05) %>% 
  set_number_format(0)
```

## Foliares

### Sanidad


```{r}
press_upa <- rio::import("data/eval_foliares.xls", sheet=2)
```

```{r}
# trt_list %>% data.frame %>% arrange(sitio, cultivo, protec,trt)
rio::import("data/eval_foliares.xls", sheet=1) %>%
  left_join(trt_list %>% filter(protec=="foliar")) %>%
  rio::export("data/eval_foliares.csv")
eval <- rio::import("data/eval_foliares.csv") 
```


### Rendimiento

```{r, eval=FALSE}
library(googlesheets4)
gs4_deauth()
"https://docs.google.com/spreadsheets/d/1Wcxxw3hzcAwpFGZS5qf1H_8utLa0UnMIG6-sztdsYug/edit?usp=sharing" %>%
  gs4_get() -> google_file
google_file %>% googlesheets4::sheet_names()
```

```{r, eval=FALSE}
# google_file %>% read_sheet(sheet = "meta") %>% 
#   filter(ensayo=="foliares") %>% 
#   dplyr::select(cultivo, localidad, cultivar, obs, logro_ensayo) %>% 
#   rio::export(file = "data/meta_foliares.csv") 
# 
meta_foliar <-  rio::import(file = "data/meta_foliares.csv")

# raw_rinde <- google_file %>% read_sheet(sheet = "cosecha", range = "A:I")
# raw_rinde %>% filter(sitio=="La Dulce", protec=="semilla", trt==3)

# dat <- left_join(raw_rinde, trt_list) %>% 
#   mutate(estrategia = replace_na(estrategia, "simple"))
# save(dat, file="data/raw.rds")
# load(file="data/raw.rds")
# dat %>%
#   select(sitio:prod) %>% 
#   filter(protec == "foliar") %>%
#   rio::export(file="data/rinde_foliares.csv")
```


```{r}
dat <-  rio::import(file="data/rinde_foliares.csv")
dat %>% 
  select(sitio, cultivo, protec, trt, prod, bq, kg_ha) %>% 
  as_hux() %>% 
  set_font_size(9) %>% 
  theme_compact() %>% 
  set_tb_padding(.05)%>% 
  set_number_format(0)
```