---
title: "Red de protección química de cereales invierno"
format: docx
---
- Coordinación gral: Segundo Fernandez Paez
- Coordinación técnica: Juan Edwards

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = F, warning = FALSE, message = FALSE)
pacman::p_load(tidyverse,
               huxtable
               )
pacman::p_load(lme4, emmeans, multcomp, performance)
conflicted::conflict_prefer("filter", "dplyr")
conflicted::conflict_prefer("select", "dplyr")
load("data/raw.rds")
theme_set(theme_gray(base_size = 12)) 
theme_set(theme_linedraw(base_size = 12)) 

dat %>% distinct(prod) %>% pull() %>% sort()
```

```{r, eval=FALSE}
library(googlesheets4)
gs4_deauth()
"https://docs.google.com/spreadsheets/d/1Wcxxw3hzcAwpFGZS5qf1H_8utLa0UnMIG6-sztdsYug/edit?usp=sharing" %>%
  gs4_get() -> google_file
```

```{r, eval=FALSE}
raw_rinde <- google_file %>% read_sheet(sheet = "cosecha", range = "A:I")
trt_list <- google_file %>% read_sheet(sheet = "trt_list", range = "A:F")
dat <- left_join(raw_rinde, trt_list) %>% 
  mutate(estrategia = replace_na(estrategia, "simple"))
save(dat, file="data/raw.rds")
```

## Curasemillas

```{r}
dat %>% 
  filter(protec == "semilla") %>% 
  filter(prod != "Sistiva_premis_2x" ) %>% 
  filter(!(sitio == "MDP" & trt ==10 & cultivo =="cebada")) %>% 
  ggplot() + 
  aes(y=prod, x=kg_ha) + 
  facet_grid(cultivo ~ sitio, scales = "free") + 
  geom_point(alpha=.2) +
  # geom_text(aes(label=trt), size=3)+
  stat_summary(fun=mean, col="red") + 
  stat_summary(aes(label=round(..x..)), fun=mean, geom="text", size=3, vjust=-.5) + 
  scale_x_continuous(breaks = scales::pretty_breaks(5), 
                     guide=guide_axis(n.dodge=2)) +
  labs(y="", x ="kg/ha", title = "")
```

## Foliares

### Cebada 

```{r, fig.height = 6, fig.width = 10}
dat %>% 
  filter(cultivo == "cebada") %>%
  filter(protec == "foliar") %>% 
  filter(!(prod == "Orquesta 1200 @Z39" & trt ==9)) %>% 
  filter(!(sitio == "Tandil" & trt ==7 & (kg_ha<3000|kg_ha>5500))) %>% 
  mutate(prod = fct_relevel(prod, "Check")) %>% 
  ggplot() + 
  aes(y=prod, x=kg_ha) + 
  facet_grid(. ~ sitio, scales = "free") +
  geom_text(aes(label=trt), size=3)+
  # geom_point(alpha=.2) +
  stat_summary(fun=mean, col="red") + 
  stat_summary(aes(label=round(..x..)), fun=mean, geom="text", size=3, vjust=-.5) + 
  scale_x_continuous(breaks = scales::pretty_breaks(4), 
                     guide=guide_axis(n.dodge=2)) +
  labs(y="", x ="kg/ha", title = "Foliares - Cebada")
```

```{r}
dat %>% 
  filter(cultivo == "cebada") %>%
  filter(protec == "foliar") %>%
  # filter(!(sitio == "Tandil" & trt ==7 & (kg_ha<3000|kg_ha>5500))) %>%
  mutate(prod = fct_relevel(prod, "Check")) %>% 
  filter(!(prod == "Cripton_600 @Z39")) %>% 
  mutate_at(vars(prod, bq, sitio), as.factor) %>% 
  droplevels()-> cebada_foliar

# cebada_foliar %>% 
#   # count(sitio)
#   group_by(sitio) %>% 
#   summarise(min_abs=min(kg_ha), 
#             min_q=quantile(kg_ha, .05))
# 
# cebada_foliar %>% 
#   group_by(sitio, prod) %>%
#   summarise(n = sum(!is.na(kg_ha)),
#             mean= mean(kg_ha, na.rm =T),
#             sd= sd(kg_ha, na.rm =T)) -> smr
```

Modelos intra-sitios

```{r}
cebada_foliar %>%
  group_by(sitio) %>%
  group_modify(~ broom::tidy(car::Anova(lmer(kg_ha ~ prod +(1|bq), data = .x)))) %>%
  mutate(p.value = scales::pvalue(p.value, add_p = TRUE))
```

```{r}
cebada_foliar %>%
  group_by(sitio) %>%
  group_modify(~ 
                 lmer(kg_ha ~ prod + (1|bq), data = .x) %>%
                 emmeans(., ~ prod, type = "response") %>%
                 cld(., Letters = letters, alpha = .1,
                     type = "response", reversed = T) %>%
                 broom::tidy() %>% 
                 rename(kg_ha = estimate) %>%
                 mutate_if(is.character, as.factor)
               ) %>% 
  group_by(sitio) %>% 
  mutate(test_kg_ha = kg_ha[prod == "Check"]) %>% 
  mutate(dif_kg = kg_ha- test_kg_ha,
         `dif_%` = (kg_ha/test_kg_ha - 1) * 100) %>% 
  select(-std.error, -df, -test_kg_ha) %>% 
  print(n=Inf)
  # group_by(prod) %>% 
  # summarise(resp=mean(`dif_%`)) %>% 
  # arrange(resp)
```

Modelo global 

```{r}
# cebada_foliar %>% count(sitio, prod) %>% print(n=Inf)
# ftable(xtabs(~prod + sitio, cebada_foliar))
cf1 <- lmer(kg_ha ~ prod + (1|sitio/bq), data=cebada_foliar)
plot(cf1)
check_heteroscedasticity(cf1) %>% plot
check_normality(cf1)%>% plot

library(nlme)
m1 <- lme(kg_ha ~ prod, 
          random = ~1 | sitio/bq, 
          weights=varIdent(form=~1|sitio), 
          method='REML', 
          data = cebada_foliar)
plot(m1)
check_heteroscedasticity(m1) %>% plot
check_normality(cf1)%>% plot

m1 %>% 
  emmeans(., ~ prod, type = "response") %>%  
  cld(., Letters = letters, alpha = .1,
      type = "response", reversed = T) %>%
  broom::tidy() %>% 
  rename(kg_ha = estimate, "tukey_10%"=.group) %>% 
  mutate(test_kg_ha = kg_ha[prod == "Check"]) %>% 
  mutate(dif_kg = kg_ha - test_kg_ha,
         `dif_%` = (kg_ha/test_kg_ha - 1) * 100) %>% 
  select(-std.error, -df, -test_kg_ha)
```

### Trigo 

```{r, fig.height = 8, fig.width = 10}
dat %>% 
  filter(cultivo == "trigo") %>%
  filter(protec == "foliar") %>% 
  filter(!(prod == "Orquesta 1200 @Z39" & trt ==10)) %>% 
  filter(!(sitio == "MDP"& trt==5	& bq ==3)) %>% 
  mutate(prod = fct_relevel(prod, "Check")) %>% 
  ggplot() + 
  aes(y=prod, 
      # col=factor(bq),  
      x=kg_ha) + 
  facet_grid(sitio~., scales = "free") + 
  # geom_text(aes(label=trt), size=3)+
  geom_point(alpha=.2) +
  stat_summary(fun=mean, col="red") + 
  stat_summary(aes(label=round(..x..)), fun=mean, geom="text", size=3, vjust=-.5) + 
  scale_x_continuous(breaks = scales::pretty_breaks(5), 
                     guide=guide_axis(n.dodge=2)) +  
  labs(y="", x="kg/ha", title = "Foliares - Trigo")
```

```{r}
dat %>% 
  filter(cultivo == "trigo") %>%
  filter(protec == "foliar") %>%
  filter(!(prod == "Orquesta 1200 @Z39" & trt ==10)) %>% 
 # filter(!(sitio == "Tandil" & trt ==7 & (kg_ha<3000|kg_ha>5500))) %>%
  mutate(prod = fct_relevel(prod, "Check")) %>% 
  # filter(!(prod == "Cripton 600 @Z39")) %>% 
  droplevels()-> trigo_foliar

# trigo_foliar %>% 
#   # count(sitio)
#   group_by(sitio) %>% 
#   summarise(min_abs=min(kg_ha), 
#             min_q=quantile(kg_ha, .05))

# cebada_foliar %>% 
#   group_by(sitio, prod) %>%
#   summarise(n = sum(!is.na(kg_ha)),
#             mean= mean(kg_ha, na.rm =T),
#             sd= sd(kg_ha, na.rm =T)) -> smr
```

Modelos intra-sitios (No se evalua globalmente ya que variaron las estrategias)

```{r}
trigo_foliar %>%
  group_by(sitio) %>%
  group_modify(~ broom::tidy(car::Anova(lmer(kg_ha ~ prod +(1|bq), data = .x)))) %>%
  mutate(p.value = scales::pvalue(p.value, add_p = TRUE))
```

```{r}
trigo_foliar %>%
  group_by(sitio) %>%
  group_modify(~ 
                 lmer(kg_ha ~ prod + (1|bq), data = .x) %>%
                 emmeans(., ~ prod, type = "response") %>%
                 cld(., Letters = letters, alpha = .1,
                     type = "response", reversed = T) %>%
                 broom::tidy() %>% 
                 rename(kg_ha = estimate) %>%
                 mutate_if(is.character, as.factor)
               ) %>% 
  group_by(sitio) %>% 
  mutate(test_kg_ha = kg_ha[prod == "Check"]) %>% 
  mutate(dif_kg = kg_ha- test_kg_ha,
         `dif_%` = (kg_ha/test_kg_ha - 1) * 100) %>% 
  select(-std.error, -df, -test_kg_ha, -contains("conf"))
# %>% 
  # group_by(prod) %>% 
  # summarise(resp=mean(`dif_%`)) %>% 
  # arrange(resp)
```

